/*
MySQL Data Transfer
Source Host: localhost
Source Database: ffxiv_server
Target Host: localhost
Target Database: ffxiv_server
Date: 5/1/2017 10:28:15 PM
*/

-- SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for characters
-- ----------------------------
CREATE TABLE "characters" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "userId" bigint NOT NULL,
  "slot" integer NOT NULL,
  "serverId" integer NOT NULL,
  "name" varchar(32) NOT NULL,
  "state" integer NOT NULL DEFAULT '0',
  "creationDate" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "isLegacy" integer DEFAULT '0',
  "doRename" integer DEFAULT '0',
  "playTime" bigint NOT NULL DEFAULT '0',
  "positionX" float NOT NULL DEFAULT '0',
  "positionY" float NOT NULL DEFAULT '0',
  "positionZ" float NOT NULL DEFAULT '0',
  "rotation" float NOT NULL DEFAULT '0',
  "actorState" integer DEFAULT '0',
  "currentZoneId" integer DEFAULT '0',
  "currentPrivateArea" varchar(32) DEFAULT NULL,
  "currentPrivateAreaType" bigint DEFAULT '0',
  "destinationZoneId" integer DEFAULT '0',
  "destinationSpawnType" smallint DEFAULT '0',
  "guardian" smallint DEFAULT '0',
  "birthDay" smallint DEFAULT '0',
  "birthMonth" smallint DEFAULT '0',
  "initialTown" smallint DEFAULT '0',
  "tribe" smallint DEFAULT '0',
  "gcCurrent" smallint DEFAULT '0',
  "gcLimsaRank" smallint DEFAULT '127',
  "gcGridaniaRank" smallint DEFAULT '127',
  "gcUldahRank" smallint DEFAULT '127',
  "currentTitle" bigint DEFAULT '0',
  "restBonus" integer DEFAULT '0',
  "achievementPoints" bigint DEFAULT '0',
  "currentActiveLinkshell" varchar(32) NOT NULL DEFAULT '',
  "homepoint" bigint NOT NULL DEFAULT '0',
  "homepointInn" smallint NOT NULL DEFAULT '0',
  PRIMARY KEY ("id")
);
