/*
MySQL Data Transfer
Source Host: localhost
Source Database: ffxiv_server
Target Host: localhost
Target Database: ffxiv_server
Date: 3/14/2020 1:00:50 PM
*/

-- SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for characters_appearance
-- ----------------------------
CREATE TABLE "characters_appearance" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "characterId" bigint NOT NULL,
  "baseId" bigint NOT NULL,
  "size" smallint NOT NULL DEFAULT '0',
  "voice" smallint NOT NULL DEFAULT '0',
  "skinColor" integer NOT NULL,
  "hairStyle" integer NOT NULL,
  "hairColor" integer NOT NULL,
  "hairHighlightColor" integer NOT NULL DEFAULT '0',
  "hairVariation" integer NOT NULL,
  "eyeColor" integer NOT NULL,
  "faceType" smallint NOT NULL DEFAULT '0',
  "faceEyebrows" smallint NOT NULL DEFAULT '0',
  "faceEyeShape" smallint NOT NULL DEFAULT '0',
  "faceIrisSize" smallint NOT NULL DEFAULT '0',
  "faceNose" smallint NOT NULL DEFAULT '0',
  "faceMouth" smallint NOT NULL DEFAULT '0',
  "faceFeatures" smallint NOT NULL,
  "ears" smallint NOT NULL DEFAULT '0',
  "characteristics" smallint NOT NULL DEFAULT '0',
  "characteristicsColor" smallint NOT NULL DEFAULT '0',
  "mainhand" bigint NOT NULL,
  "offhand" bigint NOT NULL,
  "head" bigint NOT NULL,
  "body" bigint NOT NULL,
  "hands" bigint NOT NULL,
  "legs" bigint NOT NULL,
  "feet" bigint NOT NULL,
  "waist" bigint NOT NULL,
  "neck" bigint NOT NULL DEFAULT '0',
  "leftIndex" bigint NOT NULL DEFAULT '0',
  "rightIndex" bigint NOT NULL DEFAULT '0',
  "leftFinger" bigint NOT NULL DEFAULT '0',
  "rightFinger" bigint NOT NULL DEFAULT '0',
  "leftEar" bigint NOT NULL DEFAULT '0',
  "rightEar" bigint NOT NULL DEFAULT '0',
  PRIMARY KEY ("id")
);