/*
MySQL Data Transfer
Source Host: localhost
Source Database: ffxiv_server
Target Host: localhost
Target Database: ffxiv_server
Date: 9/9/2017 2:30:21 PM
*/

-- SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for server_retainers
-- ----------------------------
CREATE TABLE "server_retainers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "actorClassId" bigint NOT NULL,
  "cdIDOffset" smallint NOT NULL DEFAULT '0',
  "placeName" integer NOT NULL,
  "conditions" smallint NOT NULL DEFAULT '0',
  "level" smallint NOT NULL,
  PRIMARY KEY ("id")
);
