-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.17 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.1.0.5464
-- --------------------------------------------------------

-- /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
-- /*!40101 SET NAMES utf8 */;
-- /*!50503 SET NAMES utf8mb4 */;
-- /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
-- /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
-- 
-- -- Dumping structure for table ffxiv_server.server_items_modifiers
CREATE TABLE IF NOT EXISTS "server_items_modifiers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "durability" integer NOT NULL DEFAULT '0',
  "mainQuality" smallint NOT NULL DEFAULT '0',
  "subQuality1" smallint NOT NULL DEFAULT '0',
  "subQuality2" smallint NOT NULL DEFAULT '0',
  "subQuality3" smallint NOT NULL DEFAULT '0',
  "param1" integer NOT NULL DEFAULT '0',
  "param2" integer NOT NULL DEFAULT '0',
  "param3" integer NOT NULL DEFAULT '0',
  "spiritbind" integer NOT NULL DEFAULT '0',
  "materia1" integer NOT NULL DEFAULT '0',
  "materia2" integer NOT NULL DEFAULT '0',
  "materia3" integer NOT NULL DEFAULT '0',
  "materia4" integer NOT NULL DEFAULT '0',
  "materia5" integer NOT NULL DEFAULT '0',
  PRIMARY KEY ("id")
);
-- 
-- /*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
-- /*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
-- /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
