/*
MySQL Data Transfer
Source Host: localhost
Source Database: ffxiv_server
Target Host: localhost
Target Database: ffxiv_server
Date: 4/15/2017 4:38:26 PM
*/

-- SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for server_linkshells
-- ----------------------------
CREATE TABLE "server_linkshells" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "crestIcon" integer NOT NULL,
  "master" bigint NOT NULL DEFAULT '0',
  "rank" smallint NOT NULL,
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records 
-- ----------------------------
