/*
MySQL Data Transfer
Source Host: localhost
Source Database: ffxiv_server
Target Host: localhost
Target Database: ffxiv_server
Date: 8/21/2016 6:17:47 PM
*/

-- SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for supportdesk_tickets
-- ----------------------------
CREATE TABLE "supportdesk_tickets" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(32) NOT NULL,
  "title" varchar(128) NOT NULL,
  "body" text NOT NULL,
  "langCode" integer NOT NULL,
  "isOpen" smallint NOT NULL DEFAULT '1',
  PRIMARY KEY ("id")
);

-- ----------------------------
-- Records 
-- ----------------------------
